### ISSUE TITLE
Theres an issue in Wiping partitions 

### ISSUE THREAD

**Issue by MisterVoidy** [Galaxy-MT6768/android_device_samsung_a31nsxx#10]
in advanced tab, some of the options like data, system (cant remember) are missing, and If I try to wipe the rest, cache and dalvik/cache it kept failing saying (permissions denied) etc etc, so whenever I tried to flash GSI, it kept booting to recovery instead of the android os itself.. or probably just to say, bootloop, until I revert it back using odin

Note: the Official Twrp for the A31 is more broken since it couldn't read the SD card and internal memory clearly lol but yeah.. wiping partitions there does the same, seems the only thing that can be wiped is the dalvik/cache partition on both recovery and yours

Specifications
Android 12 One ui 4.1
SM-A315N (SKC)

**Comment by DevZillion** [comment]
Hey 👋
In first place, system individual can't be supported since this device uses dynamic partitions, meaning that system vendor product odm are inside a super partition. A workaround would be using the fastboot that this amazing TWRP has and doing `fastboot wipe system`.
To format data you can do `fastboot -w` and about the unable to unlock warning, I'm aware of that and it's caused my stuff related to mediatek and critical partitions. Be sure to be using [TWRP](https://github.com/Galaxy-MT6768/teamwin_device_samsung_a31/releases/tag/v1.2.2_TWRP) latest release and not SkyHawk since it does not have fastboot support.

Best Regards,
Zillion
